/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/user'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIndexRouteImport } from './routes/user/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AboutUsIndexRouteImport } from './routes/about-us/index'
import { Route as UserMyAttendanceIndexRouteImport } from './routes/user/my-attendance/index'
import { Route as UserClockInOutIndexRouteImport } from './routes/user/clock-in-out/index'
import { Route as UserAccountIndexRouteImport } from './routes/user/account/index'
import { Route as AdminStaffsIndexRouteImport } from './routes/admin/staffs/index'
import { Route as AdminReportsIndexRouteImport } from './routes/admin/reports/index'
import { Route as AdminAttendanceIndexRouteImport } from './routes/admin/attendance/index'

const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserRoute,
} as any).lazy(() => import('./routes/user/index.lazy').then((d) => d.Route))
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login/index.lazy').then((d) => d.Route))
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any).lazy(() => import('./routes/admin/index.lazy').then((d) => d.Route))
const AboutUsIndexRoute = AboutUsIndexRouteImport.update({
  id: '/about-us/',
  path: '/about-us/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/about-us/index.lazy').then((d) => d.Route),
)
const UserMyAttendanceIndexRoute = UserMyAttendanceIndexRouteImport.update({
  id: '/my-attendance/',
  path: '/my-attendance/',
  getParentRoute: () => UserRoute,
} as any).lazy(() =>
  import('./routes/user/my-attendance/index.lazy').then((d) => d.Route),
)
const UserClockInOutIndexRoute = UserClockInOutIndexRouteImport.update({
  id: '/clock-in-out/',
  path: '/clock-in-out/',
  getParentRoute: () => UserRoute,
} as any).lazy(() =>
  import('./routes/user/clock-in-out/index.lazy').then((d) => d.Route),
)
const UserAccountIndexRoute = UserAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => UserRoute,
} as any).lazy(() =>
  import('./routes/user/account/index.lazy').then((d) => d.Route),
)
const AdminStaffsIndexRoute = AdminStaffsIndexRouteImport.update({
  id: '/staffs/',
  path: '/staffs/',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/staffs/index.lazy').then((d) => d.Route),
)
const AdminReportsIndexRoute = AdminReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/reports/index.lazy').then((d) => d.Route),
)
const AdminAttendanceIndexRoute = AdminAttendanceIndexRouteImport.update({
  id: '/attendance/',
  path: '/attendance/',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/attendance/index.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/user': typeof UserRouteWithChildren
  '/about-us': typeof AboutUsIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/login': typeof LoginIndexRoute
  '/user/': typeof UserIndexRoute
  '/admin/attendance': typeof AdminAttendanceIndexRoute
  '/admin/reports': typeof AdminReportsIndexRoute
  '/admin/staffs': typeof AdminStaffsIndexRoute
  '/user/account': typeof UserAccountIndexRoute
  '/user/clock-in-out': typeof UserClockInOutIndexRoute
  '/user/my-attendance': typeof UserMyAttendanceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsIndexRoute
  '/admin': typeof AdminIndexRoute
  '/login': typeof LoginIndexRoute
  '/user': typeof UserIndexRoute
  '/admin/attendance': typeof AdminAttendanceIndexRoute
  '/admin/reports': typeof AdminReportsIndexRoute
  '/admin/staffs': typeof AdminStaffsIndexRoute
  '/user/account': typeof UserAccountIndexRoute
  '/user/clock-in-out': typeof UserClockInOutIndexRoute
  '/user/my-attendance': typeof UserMyAttendanceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/user': typeof UserRouteWithChildren
  '/about-us/': typeof AboutUsIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/login/': typeof LoginIndexRoute
  '/user/': typeof UserIndexRoute
  '/admin/attendance/': typeof AdminAttendanceIndexRoute
  '/admin/reports/': typeof AdminReportsIndexRoute
  '/admin/staffs/': typeof AdminStaffsIndexRoute
  '/user/account/': typeof UserAccountIndexRoute
  '/user/clock-in-out/': typeof UserClockInOutIndexRoute
  '/user/my-attendance/': typeof UserMyAttendanceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/user'
    | '/about-us'
    | '/admin/'
    | '/login'
    | '/user/'
    | '/admin/attendance'
    | '/admin/reports'
    | '/admin/staffs'
    | '/user/account'
    | '/user/clock-in-out'
    | '/user/my-attendance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/admin'
    | '/login'
    | '/user'
    | '/admin/attendance'
    | '/admin/reports'
    | '/admin/staffs'
    | '/user/account'
    | '/user/clock-in-out'
    | '/user/my-attendance'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/user'
    | '/about-us/'
    | '/admin/'
    | '/login/'
    | '/user/'
    | '/admin/attendance/'
    | '/admin/reports/'
    | '/admin/staffs/'
    | '/user/account/'
    | '/user/clock-in-out/'
    | '/user/my-attendance/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  UserRoute: typeof UserRouteWithChildren
  AboutUsIndexRoute: typeof AboutUsIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/': {
      id: '/user/'
      path: '/'
      fullPath: '/user/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/about-us/': {
      id: '/about-us/'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/my-attendance/': {
      id: '/user/my-attendance/'
      path: '/my-attendance'
      fullPath: '/user/my-attendance'
      preLoaderRoute: typeof UserMyAttendanceIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/clock-in-out/': {
      id: '/user/clock-in-out/'
      path: '/clock-in-out'
      fullPath: '/user/clock-in-out'
      preLoaderRoute: typeof UserClockInOutIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/account/': {
      id: '/user/account/'
      path: '/account'
      fullPath: '/user/account'
      preLoaderRoute: typeof UserAccountIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/admin/staffs/': {
      id: '/admin/staffs/'
      path: '/staffs'
      fullPath: '/admin/staffs'
      preLoaderRoute: typeof AdminStaffsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports/': {
      id: '/admin/reports/'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendance/': {
      id: '/admin/attendance/'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceIndexRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAttendanceIndexRoute: typeof AdminAttendanceIndexRoute
  AdminReportsIndexRoute: typeof AdminReportsIndexRoute
  AdminStaffsIndexRoute: typeof AdminStaffsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminAttendanceIndexRoute: AdminAttendanceIndexRoute,
  AdminReportsIndexRoute: AdminReportsIndexRoute,
  AdminStaffsIndexRoute: AdminStaffsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface UserRouteChildren {
  UserIndexRoute: typeof UserIndexRoute
  UserAccountIndexRoute: typeof UserAccountIndexRoute
  UserClockInOutIndexRoute: typeof UserClockInOutIndexRoute
  UserMyAttendanceIndexRoute: typeof UserMyAttendanceIndexRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserIndexRoute: UserIndexRoute,
  UserAccountIndexRoute: UserAccountIndexRoute,
  UserClockInOutIndexRoute: UserClockInOutIndexRoute,
  UserMyAttendanceIndexRoute: UserMyAttendanceIndexRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  UserRoute: UserRouteWithChildren,
  AboutUsIndexRoute: AboutUsIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
